### ISSUE TITLE
Cannot parse the jsx flow element

### ISSUE THREAD

**Issue by sanyuan0704** [wooorm/mdxjs-rs#21]
I try to excute the following code:

```rust
compile("import { Theme } from '@theme'\n <Theme />", &Default::default())
```

The compile function is exported from `src/lib.rs`.But it failed, the error log is as follows:

```
running 1 test
thread 'tests::test_compile' panicked at 'compile: "2:11: Unexpected statement in code: only import/exports are supported"', src/lib.rs:134:88
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/result.rs:1790:5
   3: core::result::Result<T,E>::expect
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/result.rs:1069:23
   4: mdxjs::tests::test_compile
             at ./src/lib.rs:134:13
   5: mdxjs::tests::test_compile::{{closure}}
             at ./src/lib.rs:132:23
   6: core::ops::function::FnOnce::call_once
```

Is my usage not correct?

**Comment by wooorm** [comment]
Hi! You need blank lines between import/export and “markdown”.

Markdown is a whitespace-sensitive language. Whitespace is super important there. Make sure to use clear, clean, proper code for it!
